#!/usr/bin/env php
<?php

// Autoload depending on where we are standing
$project_autoload_path = __DIR__.'/../../autoload.php';
$local_autoload_path   = __DIR__.'/vendor/autoload.php';

// Prepare the autoload path for composer
$autoload_path = file_exists($project_autoload_path)
    ? $project_autoload_path
    : $local_autoload_path;

// Autoload classes
require_once $autoload_path;

// Initialize app dependencies
$dependencies = [
    'blacksmith_root_path'     => getcwd(),
    'blacksmith_commands_path' => getcwd() . DIRECTORY_SEPARATOR . 'commands',
    'blacksmith_bin_path'      => 'vendor' . DIRECTORY_SEPARATOR . 'bin' . DIRECTORY_SEPARATOR . 'blacksmith',
    'blacksmith_xml_path'      => getcwd() . DIRECTORY_SEPARATOR . 'blacksmith.xml',
    'templates' => [
        'blacksmith_xml_path' => 'templates' . DIRECTORY_SEPARATOR . 'config' . DIRECTORY_SEPARATOR . 'blacksmith.xml'
    ]
];

// Get a console instance
$config  = new Blacksmith\Config($dependencies);
$console = new Blacksmith\Console($config, $argv);

try {

    $console->handle();

} catch (Exception $e) {

    $console->getOutput()->println($e->getMessage(), 'red');
}

exit;
