#!/usr/bin/env php
<?php

$project_autoload_path = __DIR__.'/../../autoload.php';
$local_autoload_path   = __DIR__.'/vendor/autoload.php';

$autoload_path = file_exists($project_autoload_path)
    ? $project_autoload_path
    : $local_autoload_path;

// Autoload classes
require_once $autoload_path;


$console = new Blacksmith\Console($argv);

// Tell the console which are the commands
// we want available to use
$console->commands = [
    Blacksmith\Commands\HelpCommand::class,
    Blacksmith\Examples\SayHello::class,
    Blacksmith\Examples\SayBye::class
];

$console->handle();

exit;
