baseurl = "https://example.org/"
languageCode = "en-us"
title = "Blacksmith"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
    # General information
    author = "eaperezc"
    description = "A CLI helper lib for PHP."
    copyright = "Released under the MIT license"

    # Repository
    provider = "GitHub"
    repo_url = "https://github.com/eaperezc/blacksmith"

    version = "0.0.1"
    logo = "images/anvil.jpg"
    favicon = "images/anvil.jpg"

    permalink = "#"

    # Custom assets
    custom_css = []
    custom_js  = []

    # Syntax highlighting theme
    highlight_css  = ""

    [params.palette]
        primary = "teal"
        accent  = "light_blue"

    [params.font]
        text = "Ubuntu"
        code = "Ubuntu Mono"


[social]
    twitter = ""
    github  = "eaperezc"
    email   = "eaperezc@gmail.com"


[[menu.main]]
    name   = "Blacksmith"
    url    = "/"
    weight = 0

[[menu.main]]
    name   = "Getting started"
    url    = "getting-started/"
    weight = 10


[blackfriday]
    smartypants = true
    fractions = true
    smartDashes = true
    plainIDAnchors = true
